Feature/user registration
caiola/vinhos.com pull request #12
Opened 2023-05-21 16:03 UTC by caiola

2023-05-22 23:34 UTC, sergiodenboer requested changes
Too big.
MR's need to be short in scope.

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/status_description.py
> +class StatusDescription(Enum):
Why is this needed?
This is going to add multiple complexity.
This seems ok for an async architecture and we are miles away from it.

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/__init__.py
> +    app.register_blueprint(users_blueprint)
what is the difference between users and acconts?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/accounts.py
> +    __tablename__ = "account"
Why were tables renamed to sigle names?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/accounts.py
> +    nif = db.Column(db.String(50), nullable=False)
Do we need this? why?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/address.py
> +    district_id = db.Column(db.BigInteger(), nullable=True, comment="District id")
Why the _id and labels? To avoid joins? 
Why do we even need tables for this?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/address_type.py
> +    # The address type "custom" can be used as billing address
Why arer we considering billing at this stage?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/database.py
> +class Database():
Why do we need this?
This is not a model.
This should belong on a `constants.py`

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/status.py
> +"""
At this stage we do not need this.

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/models/stores.py
> +    gps_latitude = db.Column(db.String(25), nullable=False, comment="GPS coordinates, latitude")
Not needed.

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/resources/stores/resources.py
> +        return custom_response, 418
201?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/resources/users/__init__.py
> +Global error handlers
this comment makes little sense.
Can we create a error_handlers file potentially?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/resources/users/resources.py
> +            # "email": data.get("email")
missing email?

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/resources/users/resources.py
> +            "status_id": StatusType.NEW.value,
This makes little sense. This sohuld be a concertn of the context managers layer not the api

2023-05-22 23:34 UTC, sergiodenboer commented on backend/api/resources/users/resources.py
> +    def validate_payload(self, data):
This is very cahotic. IS this in the documentaton?

2023-05-23 08:48 UTC, caiola commented on backend/api/models/status_description.py
> +class StatusDescription(Enum):
- When the user register it goes to status NEW.
- User clicks on the verify link and it changes to ACTIVE.
- If later we want to implement moderation, we will change ACTIVE to PENDING while it is PENDING approval.

I will make an workflow for this and a sequence diagram.

2023-05-23 08:49 UTC, caiola commented on backend/api/__init__.py
> +    app.register_blueprint(users_blueprint)
One account can have multiple users. E.g. one wine shop can have several product editors.

2023-05-23 08:52 UTC, caiola commented on backend/api/models/accounts.py
> +    nif = db.Column(db.String(50), nullable=False)
It was renamed to "tax_number" on the next PR. It is not something to be added on the backlog, not a concern for now.

2023-05-23 08:55 UTC, caiola commented on backend/api/models/address.py
> +    district_id = db.Column(db.BigInteger(), nullable=True, comment="District id")
yes, it can be simplified.

2023-05-23 08:55 UTC, caiola commented on backend/api/resources/stores/resources.py
> +        return custom_response, 418
yes

2023-05-23 08:56 UTC, caiola commented on backend/api/resources/users/__init__.py
> +Global error handlers
when an error happens Flask is returning the error and stack trace in HTML.
I will open a issue for this

2023-05-23 08:59 UTC, caiola commented on backend/api/resources/users/resources.py
> +            # "email": data.get("email")
yes, added on the next PR

2023-05-23 09:03 UTC, caiola commented on backend/api/resources/users/resources.py
> +            "status_id": StatusType.NEW.value,
I opened an issue to refactor and make this better #17 Models - Implement validations on creation on model instead of the API endpoint #17

2023-05-23 09:04 UTC, caiola commented on backend/api/resources/users/resources.py
> +    def validate_payload(self, data):
It will improved on #17

2023-05-23 09:55 UTC, merged