Feature/user registration schema changes
caiola/vinhos.com pull request #15
Opened 2023-05-22 12:29 UTC by caiola

2023-05-22 23:13 UTC, sergiodenboer reviewed
This MR is too big for an effective review.
We should split into smaller chunks. 
Feedback loop is going to be too big.

2023-05-22 23:13 UTC, sergiodenboer commented on README.md
> +flask db migrate -m "Add account changes"
Why this log?

2023-05-22 23:13 UTC, sergiodenboer commented on README.md
> +
I do a little differently. I would say the added complexity is not needed.
There is a docker-compose file just for development.
justo do:
 `docker-compose exec app bash`

Once inside the container do all the needed commands.

Env file looks a bit like this.
```
ENVIRONMENT=DEV
MYSQL_ROOT_PASSWORD=passowrd
MYSQL_PASSWORD=12345
MYSQL_USER=vinhos
MYSQL_DATABASE=vinhos_dev
MYSQL_HOST=db
MYSQL_PORT=3306
TIMEZONE=Europe/Lisbon
```

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/abc.py
> +    def save(self, refresh=False):
why the option `refresh=False`? To retrieve the schema?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/accounts.py
> +    account_name = db.Column(db.String(60), nullable=True, comment="Account can have any name, it is an internal reference")
Why is the field nullable?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/accounts.py
> +    address_id = db.Column(db.BigInteger(), nullable=True, comment="Address id")
Isn't the adress required? 
Why is address in a different schema? This will result in a one to many relation. On the other hand ther will be the possibility of multiple adresses having the same account. Is this what we want?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/countries_dict.py
> +"""
This is probably not needed. We should use comunity packages when able.
This can be replaced by [this](https://pypi.org/project/pycountry/)

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/accounts.py
>      status_id = db.Column(db.Integer(), default=StatusType.NEW, nullable=False, comment="Status id")
Why do we need status?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/ads.py
> +        UniqueConstraint('account_id', 'title', name='ad_unique_account_id_and_title'),
Keep in mind that we still need to do data parasint.
account_id = 1 with title "foo" as to be the same as  account_id = 1 with title "Foo"

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/countries.py
> +"""
Don't really understand the need for this enum.
Please check the package [pycountry](https://pypi.org/project/pycountry/)

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/stores.py
> +    account_id = db.Column(db.Integer(), default=StatusType.NEW, nullable=False, comment="Account id")
Why a default field in a relation?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/stores.py
> +    gps_latitude = db.Column(db.String(25), nullable=True, comment="GPS coordinates, latitude")
This is PII. We probably should not store this.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/stores.py
> +    contact_phone = db.Column(db.String(50), nullable=True, comment="Phone")
Why do we need this info?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/stores.py
> +    social_facebook = db.Column(db.String(50), nullable=True, comment="Address for social network Facebook")
Social media can be some sort embedded schema instead? I potentialy see this field as a list of dicts. Don't know if mysql has support for json but I bet it does.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/models/users.py
> +    middle_name = db.Column(db.String(150), nullable=True, comment="Middle name")
Not needed?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    # email = fields.Str(required=True, validate=validate.Email(error='invalid-email'))
Remove comment.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
>  def get_by(pk: int = None, name: str = None) -> Account:
Why are we saving?
This seems to be worngly implemented.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    data_validation = {"email": data["email"]}
Why the redefinition?

`result = schema.load(**data)`

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    schema = AccountCreateSchema()
This can be defined as a constant.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    except ValidationError as err:
can we do a decorator for this instead?

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +        "account_name": "account-" + str(random.randint(100000, 10000000)),
Testing stuff. Please remove.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +        "store_name": "store-" + str(random.randint(100000, 10000000)),
Testing string.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +        # "status_id": StatusType.NEW.value,
Remove commented code.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/stores.py
> +    schema = StoreCreateSchema(unknown=EXCLUDE)
Pease define `unknown=EXCLUDE` in schema settings.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/users.py
> +    # account_id = fields.Int(required=True)
Commented please remove.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/users.py
>      return user.save()
SAving on `get_by`. This is probably wrong.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/users.py
> +        abort(400, _("A user with this email already exists. Please use a different email."))
This is wrong. The error might not error due to email only. :D

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/repositories/users.py
> +    except Exception as e:
We should not catch on broad exceptions.

2023-05-22 23:13 UTC, sergiodenboer commented on backend/api/resources/accounts/resources.py
> +        # resource_parser.add_argument(
remove comments.

2023-05-22 23:13 UTC, sergiodenboer requested changes
This MR is too big for an effective review.
We should split into smaller chunks. 
Feedback loop is going to be too big.

2023-05-22 23:13 UTC, sergiodenboer requested changes
This MR is too big for an effective review.
We should split into smaller chunks. 
Feedback loop is going to be too big.

2023-05-23 08:27 UTC, caiola commented on README.md
> +flask db migrate -m "Add account changes"
Not a log, I copy/pasted and left it there 👯

2023-05-23 08:29 UTC, caiola commented on README.md
> +
This was to solve the error of a poetry dependency "poetry 'HTTPResponse' object has no attribute 'strict'".

It is a recent issue and a pain to solve.
https://github.com/python-poetry/poetry/issues/7936

With docker compose, you caanot run the command "poetry lock" because the container "apiserver" does not start

2023-05-23 08:30 UTC, caiola commented on backend/api/models/abc.py
> +    def save(self, refresh=False):
yes, after insert, you want to get the ID of the record that was inserted.

2023-05-23 08:31 UTC, caiola commented on backend/api/models/accounts.py
> +    account_name = db.Column(db.String(60), nullable=True, comment="Account can have any name, it is an internal reference")
It will be managed by store name, this will be a internal reference field.

2023-05-23 08:37 UTC, caiola commented on backend/api/models/accounts.py
> +    address_id = db.Column(db.BigInteger(), nullable=True, comment="Address id")
Yes, this will be like Ebay, we have the billing address, delivery address, dispatch address if necessary and store addresses.

One account can have several stores.
One account will be able to manage several addresses and each address is associated with an entity.

2023-05-23 08:37 UTC, caiola commented on backend/api/repositories/users.py
> +    # account_id = fields.Int(required=True)
ok

2023-05-23 08:39 UTC, caiola commented on backend/api/repositories/users.py
> +        abort(400, _("A user with this email already exists. Please use a different email."))
Email is unique for login purposes to identify the user.

2023-05-23 08:40 UTC, caiola commented on backend/api/repositories/users.py
> +    except Exception as e:
This is a special case because of the password_hash.
I dont want to log anything in this part.

2023-05-23 08:40 UTC, caiola commented on backend/api/resources/accounts/resources.py
> +        # resource_parser.add_argument(
ok

2023-05-23 09:55 UTC, merged