DVL - Move validations to models
caiola/vinhos.com pull request #28
Opened 2023-05-23 18:05 UTC by caiola

2023-05-23 21:52 UTC, sergiodenboer requested changes

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/models/tools.py
> +        except Exception:
Dont' expect Exception. This is a last resource.
This is a odd function why can data be None? It should not be optional even
Also 
`data.get(ket)` will avoid the use of exceptions.

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/models/tools.py
> +class utils:
Naming a class utils is not great.
Also Classes should start with capital letter.

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/models/tools.py
> +    def v(data, key):
A function with only one letter as a name is not great.
Also having a function that does validate the existence of a filed in a dict should probably not exist?

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    # ############################################################################
No need for this style of comments.
Just use `# comment`

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +        "email": utils.v(data, "email")
This `utils.v` function should not be used 

`data.get("email)` should be used instead.

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    account_result = accounts.create(payload)
Can we encapsulate each resource creation into it's own function?
this private function?

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/repositories/users.py
>      except Exception as e:
WE should not except Exceptions.

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/resources/accounts/resources.py
> +            data = None
This will not work properly.
data, with this implementation has 2 types, None or dict.
I would fail the request with a HTTP 415 Unsupported Media Type possibly? We only care for Json.

2023-05-23 21:52 UTC, sergiodenboer commented on backend/api/resources/accounts/resources.py
> +            result.pop("password_hash", None)
Ths will never result in an exception.
Exception handling is not needed.

2023-05-24 14:21 UTC, caiola commented on backend/api/models/tools.py
> +        except Exception:
When the field does not exists it is None. You cannot use function .get() on None

2023-05-24 14:21 UTC, caiola commented on backend/api/models/tools.py
> +class utils:
I will change it

2023-05-24 14:22 UTC, caiola commented on backend/api/repositories/accounts.py
> +    # ############################################################################
ok

2023-05-24 14:23 UTC, caiola commented on backend/api/models/tools.py
> +    def v(data, key):
It fails when the field is not sent, this function allows to try to get the value without raising an error.

2023-05-24 14:23 UTC, caiola commented on backend/api/repositories/accounts.py
> +        "email": utils.v(data, "email")
Does not work

2023-05-24 14:25 UTC, caiola commented on backend/api/repositories/users.py
>      except Exception as e:
I want to catch everything to avoid sending password_hash to logs

2023-05-24 14:26 UTC, caiola commented on backend/api/repositories/accounts.py
> +    account_result = accounts.create(payload)
I dont get what you mean. I am calling accouns.create() from the repository

2023-05-24 14:29 UTC, caiola commented on backend/api/resources/accounts/resources.py
> +            data = None
It fails when you dont sent header application/json

2023-05-24 14:30 UTC, caiola commented on backend/api/resources/accounts/resources.py
> +            result.pop("password_hash", None)
When user is not registered by any reason (e.g. SQL issue), the exception is raised.

2023-06-07 12:46 UTC, merged