29 workflow user registration to associate user to the account
caiola/vinhos.com pull request #42
Opened 2023-06-15 15:25 UTC by caiola

2023-06-15 17:21 UTC, sergiodenboer requested changes

2023-06-15 17:21 UTC, sergiodenboer commented on backend/api/models/tools.py
> +
There is no need fo class here.
You coul live with just functions :D

2023-06-15 17:21 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +        params["account_name"] = str(name)
No need to cast. Name is already a string according to the function signature.

2023-06-15 17:21 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +        "FUNCTION-CALL": "accounts.registration()",
No need for this function call key.
Also logging calls should be  different.
This comment is for all logging instances.
`logger.debug(message, extra: {key: "string" })`

2023-06-15 17:21 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +        "account_id": utils().get_value(data=account_result, key="account_id"),
`utils.get_value`
No need for a class Utils. Convert into a module level function.
The same comment is for the other instances.

2023-06-15 17:21 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    country = pycountry.countries.get(alpha_2=data.get("country").upper())
`data.get("country, "")`. If there is no country then it will fail.

2023-06-15 17:21 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +    if country is None:
This valation should be on the schema level.
I would remove from here and let it fail.

2023-06-16 10:22 UTC, caiola commented on backend/api/models/tools.py
> +
Removed

2023-06-16 10:24 UTC, caiola commented on backend/api/repositories/accounts.py
> +        "FUNCTION-CALL": "accounts.registration()",
Removed

2023-06-16 10:25 UTC, caiola commented on backend/api/repositories/accounts.py
> +        "account_id": utils().get_value(data=account_result, key="account_id"),
Refactored

2023-06-16 10:26 UTC, caiola commented on backend/api/repositories/accounts.py
> +    country = pycountry.countries.get(alpha_2=data.get("country").upper())
Fixed

2023-06-16 10:31 UTC, caiola commented on backend/api/repositories/accounts.py
> +    if country is None:
basically if the country is not found, I am assuming Portugal by default

2023-06-16 11:09 UTC, merged