Feature/unit tests fix
caiola/vinhos.com pull request #43
Opened 2023-06-18 18:22 UTC by caiola

2023-06-21 20:12 UTC, sergiodenboer requested changes

2023-06-21 20:12 UTC, sergiodenboer commented on backend/api/repositories/accounts.py
> +def create(data: dict, errors: list) -> Union[Account, None]:
Instead of passing errors around they should be raised.
The better approach would be to create a ValidationError exception an raise the error in it.

2023-06-21 20:12 UTC, sergiodenboer commented on backend/test/api/repositories/test_registration.py
> +def test_create_new_account(app):
pytest exposes mocker.
Mocker allows you to reduce the amount of code you need.

```
def test_create_existing_account(app, mocker):
    ....
    mock_get_by =  mocker.patch("api.repositories.accounts.get_by")
    mock_get_by.side_effect = NoResultFound()
    mock_save = mocker.patch.object(Account, "save")
   
    result = create(data, errors)
    mock_save.assert_called_once()
   ....

Same comment applies to other tests.
```


```

2023-06-22 19:12 UTC, caiola commented on backend/api/repositories/accounts.py
> +def create(data: dict, errors: list) -> Union[Account, None]:
The problem is that you only receive one error and we should receive all validation errors at once.
It is an improved behaviour that will allow us to customize the frontend to show all pending errors on the form being filled.
Or else the customer will submit several times the form to overcome each validation one by one.. It is annoying.

2023-06-22 19:13 UTC, caiola commented on backend/test/api/repositories/test_registration.py
> +def test_create_new_account(app):
I will open an issue to refactor later.

2023-06-22 19:15 UTC, merged