Feature/44 registration add token validation and timestamp
caiola/vinhos.com pull request #45
Opened 2023-06-19 22:38 UTC by caiola

2023-06-20 20:27 UTC, sergiodenboer requested changes

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/address.py
> +def lowercase_enum(enum_class):
What is this for?

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/address.py
> +        lowercase_enum(AddressType),
Why lower case? If so the enums are already  lowercase.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/address.py
> +        comment="Address type (e.g. account,store,user,billing,pickup)",
Enums should be out of the comment. They might change.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/address.py
> +        db.SmallInteger(),
What is wrong with a boolean field?

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/address.py
> +    # country_id = db.Column(db.BigInteger(), nullable=True, comment="Country id")
Remove comment.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/address.py
> +    # district_id = db.Column(db.BigInteger(), nullable=True, comment="District id")
Remove coment field.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/verifications.py
> +    user_id = db.Column(db.BigInteger(), nullable=False, comment="User id")
Should be indexed.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/verifications.py
> +    action = db.Column(
Should have enums for this.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/models/verifications.py
> +    token = db.Column(
Should be indexed.
Also probably a compound user_id, token is desireble.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/repositories/registration.py
> +        return {**{"errors": errors}}
just return a dict.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/repositories/registration.py
>              "FUNCTION-CALL": "accounts.registration().user-payload",
this is not needed.
Also the logger should be calles differently.
`current_app.logger.debug(messagne, extra: {"foo": "bar"}.
No need for function call key. This is configured by the logger.
Same applies to all instances.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/repositories/verifications.py
> +def create(data: dict, errors: list) -> Union[Verification, None]:
Instead of `Union` use `Optional`.

2023-06-20 20:27 UTC, sergiodenboer commented on backend/api/repositories/verifications.py
> +    try:
This is a commom pattern. Maybe refactor into a function.

2023-06-22 14:55 UTC, caiola commented on backend/api/models/address.py
> +def lowercase_enum(enum_class):
When you specify enum AddressType it used the NAME in upper case instead of the value.

class AddressType(Enum):
    ACCOUNT = "account"

We should use everything lowercase. all tables, fields names, const values, etc, as lower case.

2023-06-22 14:55 UTC, caiola commented on backend/api/models/address.py
> +        lowercase_enum(AddressType),
It parses values in upper case, e.g. "ACCOUNT" and I want to use enum as "account".

2023-06-22 14:55 UTC, caiola commented on backend/api/models/address.py
> +    # country_id = db.Column(db.BigInteger(), nullable=True, comment="Country id")
done

2023-06-22 14:55 UTC, caiola commented on backend/api/models/address.py
> +        comment="Address type (e.g. account,store,user,billing,pickup)",
It is an "e.g." and is useful for someone who see's the description of the field

2023-06-22 14:55 UTC, caiola commented on backend/api/models/address.py
> +        db.SmallInteger(),
None, just a personal preference to avoid data type conversions on JSON and Javascript when parsing the responses.

2023-06-22 14:55 UTC, caiola commented on backend/api/models/verifications.py
> +    user_id = db.Column(db.BigInteger(), nullable=False, comment="User id")
It is with the compound index => UniqueConstraint("user_id", "action", "token", name="ad_user_action_token"),

2023-06-22 14:55 UTC, caiola commented on backend/api/models/verifications.py
> +    action = db.Column(
Code refactored

2023-06-22 14:55 UTC, caiola commented on backend/api/models/verifications.py
> +    token = db.Column(
It is already there

2023-06-22 14:55 UTC, caiola commented on backend/api/repositories/verifications.py
> +    try:
I can look into that later

2023-06-22 19:05 UTC, merged